startup: Improve “missing Python packages” error messages

diff --git a/bin/syncbin-startup b/bin/syncbin-startup
--- a/bin/syncbin-startup
+++ b/bin/syncbin-startup
@@ -122,7 +122,12 @@ printf '[=...] checking for required Python packages      \r'
 SYNCBIN_MISSING_PYTHON_PACKAGE=1
 
 function test-missing-python-package {
-    if ! py-where "$1" &> /dev/null; then
+    local module_name="$1"
+    local package_name="$1"
+    if [[ $# -ge 2 ]]; then
+        package_name="$2"
+    fi
+    if ! py-where "$module_name" &> /dev/null; then
         if [[ "$SYNCBIN_MISSING_PYTHON_PACKAGE" == "1" ]]; then
             if where clear-eol &> /dev/null; then
                 clear-eol
@@ -132,20 +137,20 @@ function test-missing-python-package {
         else
             printf ', '
         fi
-        printf "$1"
+        printf "$package_name"
     fi
 }
 
 if ! where py-where &> /dev/null; then
     echo '[ !! ] failed to check for required Python packages: py-where not found'
 elif ! py-where blessings &> /dev/null; then
-    echo '[ !! ] missing Python package “blessings”, install with `syncbin bootstrap python`'
+    echo '[ !! ] missing Python package “blessings”, install with `[sudo ]pip3 install blessings`'
 else
-    test-missing-python-package basedir
-    test-missing-python-package fancyio
+    test-missing-python-package basedir 'fenhl/python-xdg-basedir'
+    test-missing-python-package fancyio 'fenhl/fancyio'
     test-missing-python-package docopt
-    test-missing-python-package lazyjson
-    test-missing-python-package mpd
+    test-missing-python-package lazyjson 'fenhl/lazyjson'
+    test-missing-python-package mpd 'python-mpd2'
     test-missing-python-package pytz
     test-missing-python-package requests
     test-missing-python-package tzlocal
