Nicer error message when `syncbin update` fails to fetch from remote

diff --git a/syncbin-update b/syncbin-update
--- a/syncbin-update
+++ b/syncbin-update
@@ -43,8 +43,10 @@ if [[ $# -eq 0 ]]; then
     else
         OLD=$(cat version.txt)
     fi
-    git fetch --quiet readonly master
-    git fetch --quiet
+    git fetch readonly master &> /dev/null || git fetch &> /dev/null || {
+        echo '[ !! ] could not fetch syncbin update from remote'
+        exit 1
+    }
     PATCHED="n"
     if [[ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]]; then
         PATCHED="y"
