Fix some XDG_DATA_HOME fallbacks

diff --git a/syncbin-update b/syncbin-update
--- a/syncbin-update
+++ b/syncbin-update
@@ -38,7 +38,7 @@ if [[ $# -eq 0 ]]; then
     else
         cd ~/git/github.com/fenhl/syncbin/master
     fi
-    if [[ -r "${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt" ]]; then
+    if [[ -r "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" ]]; then
         OLD=$(cat "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt")
     else
         OLD=$(cat version.txt)
@@ -75,7 +75,7 @@ NEWARRAY=("${(s/./)NEW}")
 NEWMAJOR=$NEWARRAY[1]
 NEWMINOR=$NEWARRAY[2]
 
-(mkdir -p "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin" && touch "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" &> /dev/null && echo "$NEW" > "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" 2> /dev/null) || echo '[ !! ]' "Could not write to ${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt, this might break syncbin updates" >&2
+(mkdir -p "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin" && touch "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" &> /dev/null && echo "$NEW" > "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" 2> /dev/null) || echo '[ !! ]' "Could not write to ${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt, this might break syncbin updates" >&2
 
 if [[ ${NEWMAJOR} -lt ${OLDMAJOR} ]]; then
     echo '[ !! ]' "Attempted to downgrade syncbin from ${OLD} to ${NEW}, aborting" >&2
