Make versioning more stable, add mvl, restructure Python files, reïntroduce lns to the installer, and other minor tweaks

diff --git a/syncbin-update b/syncbin-update
--- a/syncbin-update
+++ b/syncbin-update
@@ -48,7 +48,11 @@ if [[ $# -eq 0 ]]; then
     else
         cd ~/hub/fenhl/syncbin
     fi
-    OLD=$(cat version.txt)
+    if [[ -r "${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt" ]]; then
+        OLD=$(cat "${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt")
+    else
+        OLD=$(cat version.txt)
+    fi
     git fetch
     if [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) ]]; then
         exit 0
@@ -76,6 +80,12 @@ OLDMINOR=$OLDARRAY[2]
 NEWARRAY=("${(s/./)NEW}")
 NEWMAJOR=$NEWARRAY[1]
 NEWMINOR=$NEWARRAY[2]
+
+if [[ -w "${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt" ]]; then
+    echo "$NEW" > "${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt"
+else
+    echo '[ !! ]' "Could not write to ${XDG_DATA_HOME:-~/.local/share}/syncbin/version.txt, this might break syncbin updates" >&2
+fi
 
 if [[ ${NEWMAJOR} -lt ${OLDMAJOR} ]]; then
     echo '[ !! ]' "Attempted to downgrade syncbin from ${OLD} to ${NEW}, aborting" >&2
@@ -108,6 +118,24 @@ if [[ ${NEWMINOR} -gt ${OLDMINOR} ]]; then
                     : # command-not-found handler already installed
                 else
                     echo '[ ** ] syncbin now supports command-not-found, install using `sudo apt-get install command-not-found`'
+                fi
+            fi
+        fi
+        if [[ ${OLDMINOR} -lt 7 ]]; then
+            if where lns &> /dev/null; then
+                # lns already installed
+            else
+                mkdir -p ~/bin &&
+                cd ~/bin
+                if (where curl &> /dev/null && curl -Ls http://www.chiark.greenend.org.uk/~sgtatham/utils/lns.tar.gz | tar -xzf -) || (where wget &> /dev/null && wget -qO - http://www.chiark.greenend.org.uk/~sgtatham/utils/lns.tar.gz | tar -xzf -); then
+                    rm -f lns.tar.gz
+                    mv lns .lnsdir
+                    mv .lnsdir/lns lns
+                    rm -rf .lnsdir
+                    chmod +x lns
+                    cd -
+                else
+                    echo '[ !! ] failed to install lns, you can install manually from http://www.chiark.greenend.org.uk/~sgtatham/utils/' >&2
                 fi
             fi
         fi
