Fix syncbin-update for bash

diff --git a/syncbin-update b/syncbin-update
--- a/syncbin-update
+++ b/syncbin-update
@@ -71,13 +71,26 @@ else
     exit 1
 fi
 
-OLDARRAY=("${(s/./)OLD}")
-OLDMAJOR=$OLDARRAY[1]
-OLDMINOR=$OLDARRAY[2]
-
-NEWARRAY=("${(s/./)NEW}")
-NEWMAJOR=$NEWARRAY[1]
-NEWMINOR=$NEWARRAY[2]
+if [[ "$0" == "-zsh" ]] || [[ "$0" == "zsh" ]]; then
+    OLDARRAY=("${(s/./)OLD}")
+    OLDMAJOR=$OLDARRAY[1]
+    OLDMINOR=$OLDARRAY[2]
+    
+    NEWARRAY=("${(s/./)NEW}")
+    NEWMAJOR=$NEWARRAY[1]
+    NEWMINOR=$NEWARRAY[2]
+elif [[ "$0" == "-bash" ]] || [[ "$0" == "bash" ]]; then
+    IFS='.' read -a OLDARRAY <<< "$OLD"
+    OLDMAJOR="${OLDARRAY[0]}"
+    OLDMINOR="${OLDARRAY[1]}"
+    
+    IFS='.' read -a NEWARRAY <<< "$NEW"
+    NEWMAJOR="${NEWARRAY[0]}"
+    NEWMINOR="${NEWARRAY[1]}"
+else
+    echo '[ !! ]' "Failed to read version number, incompatible shell"
+    exit 1
+fi
 
 (mkdir -p "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin" && touch "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" &> /dev/null && echo "$NEW" > "${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt" 2> /dev/null) || echo '[ !! ]' "Could not write to ${XDG_DATA_HOME:-${HOME}/.local/share}/syncbin/version.txt, this might break syncbin updates" >&2
 
